In [17]:
import pandas as pd

data = {
    "name": ["Иван", "Юлия"],
     "subject_1": [1, 5],
     "subject_2": [2, 5],
     "subject_3": [1, 5],
     "subject_4": [3, 5]
}

df = pd.DataFrame(data)

#       name  subject_1  subject_2  subject_3  subject_4
# 0     Иван          1          2          1          3
# 1     Юлия          5          5          5          5

In [25]:
df = pd.DataFrame(data)
df = df.set_index('name')
a = (df == 5).all(axis=1)
a.mean()

np.float64(0.5)

In [10]:
def foo(a: dict):
    a['5'] = 55
    return a

a = {
    '1': '11',
    '2': '22',
    '3': '33',
    '4': '44'
}
b = foo(a)
print(b)

{'1': '11', '2': '22', '3': '33', '4': '44', '5': 55}

In [19]:
df_t

  user_name            nps
0     Vadim  [10, 5, 7, 6]
1      Igor     [8, 10, 5]
2      Lera      [4, 8, 6]
3    Andrew  [9, 6, 2, 10]

In [35]:
users = [
    {"user_name": "Vadim", "nps": [10, 5, 7, 6]},
    {"user_name": "Igor", "nps": [8, 10, 5]},
    {"user_name": "Lera", "nps": [4, 8, 6]},
    {"user_name": "Andrew", "nps": [9, 6, 2, 10]},
]

def filtered_users(users):
    filter_users = []
    for user in users:
        if (sum(user["nps"]) / len(user["nps"])) <= 7:
            filter_users.append(user)
    filter_users.sort(key=lambda x: x["user_name"])        
    return filter_users

filtered_users(users)

[{'user_name': 'Andrew', 'nps': [9, 6, 2, 10]},
 {'user_name': 'Lera', 'nps': [4, 8, 6]},
 {'user_name': 'Vadim', 'nps': [10, 5, 7, 6]}]

In [37]:
import pandas as pd

# Создаём DataFrame
data = {
    'student': [77529, 77529, 77529, 77529, 77529, 77529],
    'subject': ['матан', 'черчение', 'черчение', 'англ.яз', 'культурология', 'ОБЖ'],
    'test_dt': ['18.06.2022', '11.06.2022', '17.06.2022', '16.06.2022', '09.06.2022', '19.06.2022'],
    'score': [5, 2, 5, 5, None, None],
    'done': [None, None, None, None, '+', '-']
}

df = pd.DataFrame(data)
df

   student        subject     test_dt  score  done
0    77529          матан  18.06.2022    5.0  None
1    77529       черчение  11.06.2022    2.0  None
2    77529       черчение  17.06.2022    5.0  None
3    77529        англ.яз  16.06.2022    5.0  None
4    77529  культурология  09.06.2022    NaN     +
5    77529            ОБЖ  19.06.2022    NaN     -

In [41]:
students = df.groupby('student').apply(lambda x: (x['score'].notna()))

/var/folders/2b/mnj6w0nn13b3lrzf9wf2gz4m0000gn/T/ipykernel_34728/2937080146.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  students = df.groupby('student').apply(lambda x: (x['score'].notna()))

In [80]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# ============================================
# ПРОИЗВОДСТВЕННЫЙ КАЛЕНДАРЬ РФ 2024-2025
# ============================================

# Праздничные дни в РФ (нерабочие дни)
holidays_2024 = [
    '2024-12-28',  # Суббота (выходной)
    '2024-12-29',  # Воскресенье (выходной)
]

holidays_2025 = [
    # Новогодние каникулы
    '2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
    '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
    # Рождество (уже в новогодних каникулах)
    # День защитника Отечества
    '2025-02-23', '2025-02-24',  # 24 февраля - перенос с субботы
    # Международный женский день
    '2025-03-08', '2025-03-09',  # 9 марта - перенос с воскресенья
    # Праздник Весны и Труда
    '2025-05-01', '2025-05-02',
    # День Победы
    '2025-05-09',
    # День России
    '2025-06-12', '2025-06-13',  # 13 июня - перенос с субботы
    # День народного единства
    '2025-11-03', '2025-11-04',  # 3 ноября - перенос, 4 - сам праздник
]

all_holidays = holidays_2024 + holidays_2025

def is_working_day(date):
    """Проверяет, является ли день рабочим"""
    date_str = date.strftime('%Y-%m-%d')
    
    # Если это праздник - не рабочий день
    if date_str in all_holidays:
        return False
    
    # Если это суббота или воскресенье - не рабочий день
    if date.weekday() >= 5:
        return False
    
    return True

# ============================================
# ГЕНЕРАЦИЯ ДАТ
# ============================================

# Последняя неделя 2024 года + весь 2025 год
start_date = datetime(2024, 12, 25)
end_date = datetime(2025, 12, 31)
all_dates = pd.date_range(start=start_date, end=end_date, freq='D')

# Список валют
currencies = ['USD', 'EUR', 'CNY']

# Базовые курсы валют
base_rates = {
    'USD': 95.0,
    'EUR': 105.0,
    'CNY': 13.5
}

# ============================================
# 1. Генерация таблицы cur_tbl (ТОЛЬКО РАБОЧИЕ ДНИ)
# ============================================

cur_data = []

for currency in currencies:
    base_rate = base_rates[currency]
    last_rate = base_rate  # Храним последний курс для плавности
    
    for date in all_dates:
        if is_working_day(date):
            # Добавляем небольшую случайную вариацию к последнему курсу
            rate_change = np.random.uniform(-1.5, 1.5)
            last_rate = last_rate + rate_change
            # Ограничиваем отклонение от базового курса
            last_rate = max(base_rate - 10, min(base_rate + 10, last_rate))
            
            cur_data.append({
                'dt': date.strftime('%Y-%m-%d'),
                'currency': currency,
                'cur_rate': round(last_rate, 2)
            })

cur_tbl = pd.DataFrame(cur_data)

# ============================================
# 2. Генерация таблицы trx_tbl (КАЖДЫЙ ДЕНЬ)
# ============================================

trx_data = []

for currency in currencies:
    for date in all_dates:
        # Больше транзакций в рабочие дни
        if is_working_day(date):
            trx_amount = np.random.uniform(10000, 50000)
        else:  # Выходной или праздник
            trx_amount = np.random.uniform(3000, 15000)
        
        trx_data.append({
            'dt': date.strftime('%Y-%m-%d'),
            'currency': currency,
            'trx': round(trx_amount, 2)
        })

trx_tbl = pd.DataFrame(trx_data)

# ============================================
# 3. ВЫВОД ПРИМЕРОВ
# ============================================

print("="*80)
print("ТАБЛИЦА cur_tbl (курсы валют - ТОЛЬКО РАБОЧИЕ ДНИ)")
print("="*80)
print("\n📅 Последняя неделя 2024 года:")
print(cur_tbl[cur_tbl['dt'].str.startswith('2024-12')].head(10))

print("\n📅 Начало 2025 года (после новогодних каникул):")
print(cur_tbl[cur_tbl['dt'].str.startswith('2025-01')].head(15))

print(f"\n✅ Всего записей в cur_tbl: {len(cur_tbl)}")
print(f"✅ Рабочих дней в периоде: {len(cur_tbl) // len(currencies)}")

print("\n" + "="*80)
print("ТАБЛИЦА trx_tbl (транзакции - КАЖДЫЙ КАЛЕНДАРНЫЙ ДЕНЬ)")
print("="*80)
print("\n📅 Последняя неделя 2024 года:")
print(trx_tbl[trx_tbl['dt'].str.startswith('2024-12')].head(15))

print("\n📅 Новогодние праздники 2025:")
print(trx_tbl[(trx_tbl['dt'] >= '2025-01-01') & (trx_tbl['dt'] <= '2025-01-10')].head(30))

print(f"\n✅ Всего записей в trx_tbl: {len(trx_tbl)}")
print(f"✅ Календарных дней в периоде: {len(trx_tbl) // len(currencies)}")

# ============================================
# 4. ПРОВЕРКА ПРАЗДНИЧНЫХ ДНЕЙ
# ============================================

print("\n" + "="*80)
print("ПРОВЕРКА: есть ли курсы на праздничные дни?")
print("="*80)

holiday_check = cur_tbl[cur_tbl['dt'].isin(holidays_2025[:15])].sort_values('dt')
if len(holiday_check) > 0:
    print("❌ ОШИБКА! Найдены курсы на праздничные дни:")
    print(holiday_check)
else:
    print("✅ ВСЁ ПРАВИЛЬНО! На праздничные дни курсов нет")

print("\nПроверим конкретные даты:")
test_dates = ['2024-12-25', '2024-12-28', '2024-12-29', '2025-01-01', '2025-01-02', '2025-01-09', '2025-01-10']
for test_date in test_dates:
    has_rate = test_date in cur_tbl['dt'].values
    date_obj = datetime.strptime(test_date, '%Y-%m-%d')
    is_working = is_working_day(date_obj)
    status = "✅ рабочий" if is_working else "❌ выходной/праздник"
    rate_status = "есть курс" if has_rate else "НЕТ курса"
    print(f"  {test_date} ({date_obj.strftime('%A'):>10}) - {status:25} - {rate_status}")

================================================================================
ТАБЛИЦА cur_tbl (курсы валют - ТОЛЬКО РАБОЧИЕ ДНИ)
================================================================================

📅 Последняя неделя 2024 года:
             dt currency  cur_rate
0    2024-12-25      USD     93.50
1    2024-12-26      USD     94.15
2    2024-12-27      USD     93.16
3    2024-12-30      USD     91.98
4    2024-12-31      USD     91.19
252  2024-12-25      EUR    106.40
253  2024-12-26      EUR    106.22
254  2024-12-27      EUR    105.90
255  2024-12-30      EUR    106.94
256  2024-12-31      EUR    106.72

📅 Начало 2025 года (после новогодних каникул):
            dt currency  cur_rate
5   2025-01-09      USD     90.83
6   2025-01-10      USD     90.76
7   2025-01-13      USD     89.39
8   2025-01-14      USD     90.80
9   2025-01-15      USD     91.45
10  2025-01-16      USD     90.92
11  2025-01-17      USD     90.37
12  2025-01-20      USD     90.22
13  2025-01-21      USD     90.60
14  2025-01-22      USD     89.54
15  2025-01-23      USD     88.60
16  2025-01-24      USD     89.68
17  2025-01-27      USD     88.95
18  2025-01-28      USD     88.59
19  2025-01-29      USD     89.71

✅ Всего записей в cur_tbl: 756
✅ Рабочих дней в периоде: 252

================================================================================
ТАБЛИЦА trx_tbl (транзакции - КАЖДЫЙ КАЛЕНДАРНЫЙ ДЕНЬ)
================================================================================

📅 Последняя неделя 2024 года:
             dt currency       trx
0    2024-12-25      USD  19076.03
1    2024-12-26      USD  47171.23
2    2024-12-27      USD  38697.38
3    2024-12-28      USD  12151.84
4    2024-12-29      USD   5417.54
5    2024-12-30      USD  19367.78
6    2024-12-31      USD  30850.71
372  2024-12-25      EUR  44011.95
373  2024-12-26      EUR  27362.84
374  2024-12-27      EUR  47140.88
375  2024-12-28      EUR  10083.59
376  2024-12-29      EUR  10560.09
377  2024-12-30      EUR  43816.77
378  2024-12-31      EUR  21872.01
744  2024-12-25      CNY  11032.29

📅 Новогодние праздники 2025:
             dt currency       trx
7    2025-01-01      USD   5065.20
8    2025-01-02      USD   6665.18
9    2025-01-03      USD   6857.55
10   2025-01-04      USD   4915.56
11   2025-01-05      USD   5462.19
12   2025-01-06      USD  12462.62
13   2025-01-07      USD   5006.35
14   2025-01-08      USD   3341.49
15   2025-01-09      USD  35174.20
16   2025-01-10      USD  49039.32
379  2025-01-01      EUR   7251.19
380  2025-01-02      EUR  13871.42
381  2025-01-03      EUR  13811.56
382  2025-01-04      EUR  14717.79
383  2025-01-05      EUR  13822.06
384  2025-01-06      EUR   4528.46
385  2025-01-07      EUR  12884.69
386  2025-01-08      EUR   7918.06
387  2025-01-09      EUR  49632.05
388  2025-01-10      EUR  28891.24
751  2025-01-01      CNY  11161.90
752  2025-01-02      CNY   3697.61
753  2025-01-03      CNY  14149.40
754  2025-01-04      CNY   5670.25
755  2025-01-05      CNY  14996.08
756  2025-01-06      CNY   5058.27
757  2025-01-07      CNY  12258.56
758  2025-01-08      CNY   5680.95
759  2025-01-09      CNY  13233.87
760  2025-01-10      CNY  44997.33

✅ Всего записей в trx_tbl: 1116
✅ Календарных дней в периоде: 372

================================================================================
ПРОВЕРКА: есть ли курсы на праздничные дни?
================================================================================
✅ ВСЁ ПРАВИЛЬНО! На праздничные дни курсов нет

Проверим конкретные даты:
  2024-12-25 ( Wednesday) - ✅ рабочий                 - есть курс
  2024-12-28 (  Saturday) - ❌ выходной/праздник       - НЕТ курса
  2024-12-29 (    Sunday) - ❌ выходной/праздник       - НЕТ курса
  2025-01-01 ( Wednesday) - ❌ выходной/праздник       - НЕТ курса
  2025-01-02 (  Thursday) - ❌ выходной/праздник       - НЕТ курса
  2025-01-09 (  Thursday) - ✅ рабочий                 - есть курс
  2025-01-10 (    Friday) - ✅ рабочий                 - есть курс

In [64]:
import pandasql as psql

# Метод для выполнения SQL-запроса
def execute_sql_query(query):
    return psql.sqldf(query, {'df': df})

In [61]:
trx_data[:3]

[{'dt': '2025-01-01', 'currency': 'USD', 'trx': 32603.41},
 {'dt': '2025-01-02', 'currency': 'USD', 'trx': 40865.08},
 {'dt': '2025-01-03', 'currency': 'USD', 'trx': 29955.83}]

In [62]:
trx_tbl.head(2)

           dt currency       trx
0  2025-01-01      USD  32603.41
1  2025-01-02      USD  40865.08

In [67]:
import pandasql as psql

# Метод для выполнения SQL-запроса
def execute_sql_query(query):
    # pandasql использует локальные переменные как таблицы
    # Нужно передать их в globals() или locals()
    return psql.sqldf(query, globals())

In [99]:
execute_sql_query("""
select
  *
from
  trx_tbl
""")

              dt currency       trx
0     2024-12-25      USD  19076.03
1     2024-12-26      USD  47171.23
2     2024-12-27      USD  38697.38
3     2024-12-28      USD  12151.84
4     2024-12-29      USD   5417.54
...          ...      ...       ...
1111  2025-12-27      CNY   3613.58
1112  2025-12-28      CNY  14451.10
1113  2025-12-29      CNY  15691.45
1114  2025-12-30      CNY  38339.13
1115  2025-12-31      CNY  12717.05

[1116 rows x 3 columns]

In [98]:
execute_sql_query("""
select
  *
from
  cur_tbl
""")

             dt currency  cur_rate
0    2024-12-25      USD     93.50
1    2024-12-26      USD     94.15
2    2024-12-27      USD     93.16
3    2024-12-30      USD     91.98
4    2024-12-31      USD     91.19
..          ...      ...       ...
751  2025-12-25      CNY      7.63
752  2025-12-26      CNY      8.02
753  2025-12-29      CNY      7.42
754  2025-12-30      CNY      5.98
755  2025-12-31      CNY      7.14

[756 rows x 3 columns]

In [133]:
execute_sql_query("""
select
  trx.dt,
  trx.currency,
  cur.*,
(select max(cur_rate)
          from cur_tbl cur2
          where cur2.currency = trx.currency
          and cur2.dt < trx.dt) as l_cur
from
  trx_tbl trx
left join
  cur_tbl cur on trx.dt = cur.dt
  and trx.currency = cur.currency
where 
  trx.dt <= '2024-12-29'
order by
  trx.dt   
""")

            dt currency          dt currency  cur_rate   l_cur
0   2024-12-25      USD  2024-12-25      USD     93.50     NaN
1   2024-12-25      EUR  2024-12-25      EUR    106.40     NaN
2   2024-12-25      CNY  2024-12-25      CNY     12.04     NaN
3   2024-12-26      USD  2024-12-26      USD     94.15   93.50
4   2024-12-26      EUR  2024-12-26      EUR    106.22  106.40
5   2024-12-26      CNY  2024-12-26      CNY     12.52   12.04
6   2024-12-27      USD  2024-12-27      USD     93.16   94.15
7   2024-12-27      EUR  2024-12-27      EUR    105.90  106.40
8   2024-12-27      CNY  2024-12-27      CNY     11.89   12.52
9   2024-12-28      USD        None     None       NaN   94.15
10  2024-12-28      EUR        None     None       NaN  106.40
11  2024-12-28      CNY        None     None       NaN   12.52
12  2024-12-29      USD        None     None       NaN   94.15
13  2024-12-29      EUR        None     None       NaN  106.40
14  2024-12-29      CNY        None     None       NaN   12.52

In [128]:
execute_sql_query("""
select
  trx.dt,
  trx.currency,
  cur.*,
  case 
    when cur.cur_rate is not null then cur.cur_rate
    else (select max(cur_rate)
          from cur_tbl cur2
          where cur2.currency = trx.currency
          and cur2.dt < trx.dt)
  end as l_cur
from
  trx_tbl trx
left join
  cur_tbl cur on trx.dt = cur.dt
  and trx.currency = cur.currency
where 
  trx.dt <= '2024-12-29'
order by
  trx.dt    
""")

            dt currency          dt currency  cur_rate   l_cur
0   2024-12-25      USD  2024-12-25      USD     93.50   93.50
1   2024-12-25      EUR  2024-12-25      EUR    106.40  106.40
2   2024-12-25      CNY  2024-12-25      CNY     12.04   12.04
3   2024-12-26      USD  2024-12-26      USD     94.15   94.15
4   2024-12-26      EUR  2024-12-26      EUR    106.22  106.22
5   2024-12-26      CNY  2024-12-26      CNY     12.52   12.52
6   2024-12-27      USD  2024-12-27      USD     93.16   93.16
7   2024-12-27      EUR  2024-12-27      EUR    105.90  105.90
8   2024-12-27      CNY  2024-12-27      CNY     11.89   11.89
9   2024-12-28      USD        None     None       NaN   94.15
10  2024-12-28      EUR        None     None       NaN  106.40
11  2024-12-28      CNY        None     None       NaN   12.52
12  2024-12-29      USD        None     None       NaN   94.15
13  2024-12-29      EUR        None     None       NaN  106.40
14  2024-12-29      CNY        None     None       NaN   12.52

# Нюансы A/B тестирования для Звука

Отличный вопрос! Музыкальный стриминг имеет специфические особенности, которые создают уникальные челленджи для экспериментов.

---

## 1. Network Effects и Spillover (Сетевые эффекты и перетекание)

### **Проблема: Социальные фичи нарушают независимость групп**

```
┌──────────────────────────────────────────────────┐
│ КЛАССИЧЕСКАЯ A/B ТЕСТ ASSUMPTION                 │
├──────────────────────────────────────────────────┤
│                                                   │
│ Assumption (Предположение):                      │
│ Control и Test группы НЕЗАВИСИМЫ                 │
│ Действия users в Test НЕ влияют на Control       │
│                                                   │
│ Reality для Звука: ❌ НАРУШАЕТСЯ!                │
│                                                   │
│ Причины:                                         │
│ 1. Collaborative Playlists (Совместные плейлисты)│
│    ├─ User A (Test): создал плейлист             │
│    └─ User B (Control): видит и слушает его      │
│    → B получает "treatment" косвенно!            │
│                                                   │
│ 2. Social Sharing (Социальный обмен)             │
│    ├─ User A (Test): делится треком в VK         │
│    └─ User B (Control): кликает и слушает        │
│    → Spillover effect (эффект перетекания)       │
│                                                   │
│ 3. Referral Program (Реферальная программа)      │
│    ├─ User A (Test): получил новый реферальный   │
│    │                  бонус (2 месяца вместо 1)  │
│    └─ User B (Control): получил приглашение с    │
│    │                     улучшенным оффером       │
│    → Control "заражен" treatment                 │
│                                                   │
│ 4. Content Discovery (Открытие контента)         │
│    ├─ Test: новый алгоритм рекомендаций          │
│    ├─ Test users: слушают новые треки чаще       │
│    └─ Эти треки становятся "популярными"         │
│    → Control users: видят их в "Топ чартах"      │
│    → Indirect exposure к treatment               │
│                                                   │
└──────────────────────────────────────────────────┘
```

---

### **Решение 1: Cluster Randomization (Кластерная рандомизация)**

**Вместо user-level, делим по кластерам:**

```python
# Плохо: User-level randomization
def assign_variant_bad(user_id):
    return hash(user_id) % 2  # 0 = Control, 1 = Test
    # Problem: Friends могут быть в разных группах!

# Хорошо: Social cluster randomization
def assign_variant_good(user_id):
    # Step 1: Определяем social cluster пользователя
    social_cluster_id = get_social_cluster(user_id)
    # Social cluster = граф друзей, которые взаимодействуют
    
    # Step 2: Рандомизируем на уровне кластера
    return hash(social_cluster_id) % 2
    
def get_social_cluster(user_id):
    """
    Определяет social cluster через:
    - Collaborative playlists connections
    - Frequent sharing interactions
    - Referral chains
    """
    # Community detection algorithm (Louvain, etc)
    return social_graph.find_cluster(user_id)
```

**Пример:**
```
Кластер 1 (друзья/коллеги):
├─ User A, B, C, D, E → все в Test
└─ Слушают collaborative playlists вместе

Кластер 2 (семья):
├─ User F, G, H → все в Control
└─ Делятся музыкой между собой

Result: Минимизируем spillover внутри кластеров
```

---

### **Решение 2: Geo-based Randomization (Географическая рандомизация)**

**Для фич с сильным local network effect:**

```python
def assign_variant_by_geo(user_id):
    """
    Рандомизация по городу/региону
    """
    city = get_user_city(user_id)
    
    # Все пользователи в одном городе в одной группе
    return hash(city) % 2
    
# Пример: Москва → Test, Питер → Control
# Все москвичи получают новую фичу
# Минимизируем межгородской spillover
```

**Когда использовать:**
- ✅ Referral programs
- ✅ Viral sharing features
- ✅ Local playlists/recommendations
- ❌ НЕ для global features (например, UI changes)

---

### **Решение 3: Switchback Experiments (Переключающиеся эксперименты)**

**Для сильно "заразных" фич:**

```
Вместо A/B, делаем временное переключение:

Week 1: ВСЕ users → Control
Week 2: ВСЕ users → Test
Week 3: ВСЕ users → Control
Week 4: ВСЕ users → Test
...

Анализируем разницу между периодами
Минимизируем network effects (все в одной группе)
```

**Подходит для:**
- Marketplace changes (двусторонние рынки)
- Content recommendation algorithms
- Social features

---

## 2. Long-term Effects и Novelty Bias (Долгосрочные эффекты и эффект новизны)

### **Проблема: Краткосрочные тесты не показывают истинный эффект**

```
┌──────────────────────────────────────────────────┐
│ NOVELTY EFFECT (Эффект новизны)                  │
├──────────────────────────────────────────────────┤
│                                                   │
│ Scenario: Тестируем новый дизайн player screen   │
│                                                   │
│ Week 1-2 (Test period):                          │
│ ├─ Users: "О, новый дизайн! Интересно!"         │
│ ├─ Engagement: ↑ +15% 🎉                         │
│ └─ Decision: Ship it! ✅                         │
│                                                   │
│ Week 3-4 (After launch):                         │
│ ├─ Users: "Привык... обычный дизайн"            │
│ ├─ Engagement: вернулся к baseline               │
│ └─ Reality: No real improvement ❌               │
│                                                   │
│ ROOT CAUSE:                                      │
│ Novelty привлекает внимание временно              │
│ НЕ является true product improvement             │
│                                                   │
└──────────────────────────────────────────────────┘
```

**Примеры для Звука:**

```
1. Новый плеер UI
   Week 1: +12% session duration (novelty!)
   Week 4: +2% session duration (true effect)

2. Новые recommendation cards
   Week 1: +25% CTR (любопытство!)
   Week 8: +8% CTR (real improvement)

3. Gamification badges
   Week 1: +40% engagement (новая игрушка!)
   Month 2: +5% engagement (novelty wore off)
```

---

### **Решение 1: Longer Test Duration (Более длительные тесты)**

```python
# Плохо: Standard 2-week test
test_duration = 14  # days
# Проблема: Захватываем novelty, пропускаем true effect

# Хорошо: Extended test для behavioral changes
test_duration = 42  # days (6 weeks)
# Capture: novelty spike → decline → stabilization

# Анализ по временным окнам:
def analyze_time_decay(test_data):
    """
    Анализируем эффект по неделям
    """
    results = {
        'week_1': calculate_lift(test_data, week=1),   # Novelty
        'week_2': calculate_lift(test_data, week=2),   # Transition
        'week_4': calculate_lift(test_data, week=4),   # Stabilizing
        'week_6': calculate_lift(test_data, week=6),   # True effect
    }
    
    # Decision based on week 4-6, NOT week 1-2
    true_effect = mean(results['week_4'], results['week_6'])
    
    return true_effect
```

**Рекомендации по длительности:**

| Type of Change | Standard Duration | Recommended for Звук |
|----------------|-------------------|----------------------|
| UI/UX changes | 2 weeks | **4-6 weeks** (novelty) |
| Algorithm changes | 2-3 weeks | **6-8 weeks** (learning) |
| Pricing changes | 1-2 weeks | **3 months** (subscription cycle) |
| Social features | 2 weeks | **8-12 weeks** (network effects) |
| Onboarding changes | 1-2 weeks | **4 weeks** (cohort maturation) |

---

### **Решение 2: Holdout Group (Контрольная группа на длительный срок)**

```
Запускаем фичу для всех, НО:
Оставляем 5-10% в permanent Control

Timeline:
├─ Week 0-6: A/B test (50/50)
├─ Week 6: Ship to 90% (Test wins!)
└─ Week 6+: 10% остаются в Control forever

Мониторим долгосрочно:
├─ Month 3: Effect still positive? ✅
├─ Month 6: Effect maintained? ⚠️
└─ Month 12: Long-term impact clear

If Month 12 shows no effect or negative:
→ Rollback или iterate
```

---

### **Решение 3: Cohort-based Analysis (Когортный анализ)**

```sql
-- Анализируем по когортам входа в тест
WITH test_cohorts AS (
    SELECT 
        user_id,
        variant,
        DATE(first_exposure) as cohort_date,
        DATEDIFF(activity_date, first_exposure) as days_since_exposure
    FROM ab_test_exposure
    JOIN user_activity USING (user_id)
    WHERE test_name = 'new_recommendations_algo'
)

SELECT 
    cohort_date,
    days_since_exposure,
    variant,
    AVG(listening_hours) as avg_hours,
    
    -- Week 1 effect (novelty)
    AVG(CASE WHEN days_since_exposure <= 7 THEN listening_hours END) as week_1_hours,
    
    -- Week 6 effect (stabilized)
    AVG(CASE WHEN days_since_exposure BETWEEN 35 AND 42 THEN listening_hours END) as week_6_hours
    
FROM test_cohorts
GROUP BY cohort_date, days_since_exposure, variant;
```

**Visualization:**
```
Listening Hours over Time:

       │      ╱── Test (Week 1: +15%)
 Hours │    ╱
       │  ╱
       │╱────── Test (Week 6: +5% true effect)
       ├─────────── Control (stable)
       │
       └────────────────────────────────→
         Week 1    Week 2    Week 6    Time
```

---

## 3. Music Content Effects (Эффекты музыкального контента)

### **Проблема: Внешние факторы влияют на метрики**

```
┌──────────────────────────────────────────────────┐
│ EXTERNAL CONTENT FACTORS                         │
├──────────────────────────────────────────────────┤
│                                                   │
│ 1. New Album Releases (Новые релизы альбомов)   │
│    ├─ Популярный артист выпустил альбом          │
│    ├─ Week of release: Listening ↑ 30%           │
│    └─ Problem: Это эффект альбома, не теста!     │
│                                                   │
│ 2. Seasonal Effects (Сезонные эффекты)           │
│    ├─ Лето: Больше outdoor, меньше прослушивания │
│    ├─ Зима: Больше indoor, больше прослушивания  │
│    ├─ Праздники: Spike в новогодней музыке       │
│    └─ Problem: Seasonality маскирует treatment    │
│                                                   │
│ 3. Cultural Events (Культурные события)          │
│    ├─ Евровидение: Spike в европейской музыке    │
│    ├─ ЧМ по футболу: Больше patriotic music      │
│    └─ Problem: One-time events влияют на поведение│
│                                                   │
│ 4. Trending Content (Трендовый контент)          │
│    ├─ Viral TikTok song                          │
│    ├─ Все ищут и слушают этот трек              │
│    └─ Problem: Organic trend, не эффект теста    │
│                                                   │
│ 5. Competitor Actions (Действия конкурентов)     │
│    ├─ Spotify запустил эксклюзивный подкаст      │
│    ├─ Users временно уходят туда                 │
│    └─ Problem: External shock к retention        │
│                                                   │
└──────────────────────────────────────────────────┘
```

---

### **Решение 1: Content-Aware Stratification (Стратификация по контенту)**

```python
def stratified_randomization(users):
    """
    Рандомизация с учетом music preferences
    """
    strata = []
    
    # Stratify by primary genre preference
    genres = ['Rock', 'Pop', 'Hip-Hop', 'Electronic', 'Classical', 'Other']
    
    for genre in genres:
        genre_users = [u for u in users if u.primary_genre == genre]
        
        # 50/50 split within each genre
        n_test = len(genre_users) // 2
        random.shuffle(genre_users)
        
        test_users = genre_users[:n_test]
        control_users = genre_users[n_test:]
        
        strata.append({
            'genre': genre,
            'test': test_users,
            'control': control_users
        })
    
    return strata

# Benefit: Если Taylor Swift выпустила альбом,
#          Pop fans в Test и Control equally affected
#          → Content event не искажает результат
```

---

### **Решение 2: Event-Based Exclusion Windows (Исключение периодов событий)**

```python
# Определяем "dirty periods" для исключения из анализа
EXCLUSION_EVENTS = [
    {
        'event': 'New Year',
        'dates': ('2024-12-25', '2025-01-10'),
        'reason': 'Holiday music spike, atypical behavior'
    },
    {
        'event': 'Eurovision 2025',
        'dates': ('2025-05-10', '2025-05-20'),
        'reason': 'Event-driven content consumption'
    },
    {
        'event': 'Summer Vacation',
        'dates': ('2025-07-01', '2025-08-15'),
        'reason': 'Seasonal drop in indoor listening'
    }
]

def clean_test_data(test_results, exclusion_events):
    """
    Исключаем периоды с аномальными событиями
    """
    cleaned_data = test_results.copy()
    
    for event in exclusion_events:
        start_date, end_date = event['dates']
        
        # Remove data from this period
        cleaned_data = cleaned_data[
            ~(cleaned_data['date'].between(start_date, end_date))
        ]
        
        logging.info(f"Excluded {event['event']}: {event['reason']}")
    
    return cleaned_data
```

---

### **Решение 3: Diff-in-Diff (Difference-in-Differences)**

**Контролируем external shocks через baseline trends:**

```python
def difference_in_differences(test_data, control_data, pre_period, post_period):
    """
    Diff-in-Diff для контроля external effects
    
    Logic:
    - Измеряем trend в Control (captures external events)
    - Измеряем trend в Test
    - Difference of differences = true treatment effect
    """
    
    # Pre-period (до теста)
    test_pre = test_data[pre_period].mean()
    control_pre = control_data[pre_period].mean()
    
    # Post-period (во время теста)
    test_post = test_data[post_period].mean()
    control_post = control_data[post_period].mean()
    
    # Differences
    test_diff = test_post - test_pre
    control_diff = control_post - control_pre
    
    # Diff-in-Diff (true treatment effect)
    treatment_effect = test_diff - control_diff
    
    return {
        'treatment_effect': treatment_effect,
        'test_change': test_diff,
        'control_change': control_diff,  # External factors
        'adjusted': True
    }
```

**Example:**
```
Scenario: Тестируем новые рекомендации
          Во время теста: Taylor Swift выпустила альбом

Pre-test listening:
├─ Test: 15 hours/week
└─ Control: 15 hours/week

Post-test listening:
├─ Test: 20 hours/week (+5 hours)
└─ Control: 18 hours/week (+3 hours)

Naive analysis:
Effect = 20 - 15 = +5 hours ❌ WRONG!
Includes Taylor Swift effect!

Diff-in-Diff:
Effect = (20-15) - (18-15) = +2 hours ✅ CORRECT!
Removes external album effect
```

---

## 4. Primacy Effects и Learning Curves (Эффекты первичности и кривые обучения)

### **Проблема: Пользователи должны "научиться" новой фиче**

```
┌──────────────────────────────────────────────────┐
│ LEARNING CURVE EFFECT                            │
├──────────────────────────────────────────────────┤
│                                                   │
│ Example: Новый алгоритм voice commands           │
│                                                   │
│ Week 1 (Test): Voice success rate 75%            │
│ ├─ Users: "Как это работает?"                   │
│ ├─ Пробуют неоптимальные команды                 │
│ └─ Frustration, низкий success rate              │
│                                                   │
│ Week 4 (Test): Voice success rate 92%            │
│ ├─ Users: Научились правильным командам          │
│ ├─ Знают, что работает                           │
│ └─ Much better experience                        │
│                                                   │
│ Problem: Week 1 results ≠ true steady state      │
│                                                   │
│ If мы остановим тест на Week 1:                  │
│ → Reject good feature из-за learning curve! ❌   │
│                                                   │
└──────────────────────────────────────────────────┘
```

**Другие примеры:**

```
1. Новый UI для создания плейлистов
   Week 1: -10% playlist creation (confusion)
   Week 6: +15% playlist creation (learned new flow) ✅

2. Новая система навигации
   Week 1: +20% session duration (exploration)
   Week 3: +5% session duration (true improvement)

3. Изменили keyboard shortcuts
   Week 1: -30% power user engagement (переучивание)
   Week 8: +10% engagement (mastered new shortcuts) ✅
```

---

### **Решение 1: Exclude Ramp-up Period (Исключаем период разгона)**

```python
def analyze_post_rampup(test_data, rampup_days=14):
    """
    Анализируем только после learning period
    """
    # Exclude first 2 weeks (learning curve)
    stable_data = test_data[test_data['days_in_test'] > rampup_days]
    
    # Analyze steady-state behavior
    treatment_effect = calculate_effect(stable_data)
    
    return {
        'effect': treatment_effect,
        'note': f'Excluded first {rampup_days} days (ramp-up period)',
        'stable_state': True
    }
```

---

### **Решение 2: Cohort Maturation Analysis (Анализ зрелости когорты)**

```sql
-- Сравниваем users на одинаковом этапе зрелости
WITH user_maturity AS (
    SELECT 
        user_id,
        variant,
        activity_date,
        days_since_first_exposure,
        listening_hours,
        
        -- Group by maturity buckets
        CASE 
            WHEN days_since_first_exposure <= 7 THEN 'Week_1_Learning'
            WHEN days_since_first_exposure <= 28 THEN 'Week_2-4_Adapting'
            WHEN days_since_first_exposure > 28 THEN 'Month_2+_Stable'
        END as maturity_stage
    FROM test_exposure
    JOIN user_activity USING (user_id)
)

SELECT 
    maturity_stage,
    variant,
    AVG(listening_hours) as avg_hours,
    STDDEV(listening_hours) as std_hours
FROM user_maturity
GROUP BY maturity_stage, variant;

-- Compare ONLY stable state (Month 2+)
-- Это true treatment effect после learning
```

---

### **Решение 3: Grandfathering (Дедушкина оговорка) для Incumbent Users**

```
Problem: Existing users привыкли к старому
         Новые users сразу видят новое

Solution: Split analysis

Segment 1: Incumbent Users (existing)
├─ Control: Старый опыт (привычный)
├─ Test: Новый опыт (нужно переучиваться)
└─ Expect: Negative short-term, possibly positive long-term

Segment 2: New Users
├─ Control: Старый опыт (учатся с нуля)
├─ Test: Новый опыт (тоже учатся с нуля)
└─ Expect: Более честное сравнение, меньше bias

Decision Rule:
If (new_users_test > new_users_control) AND
   (incumbent_users_test ≈ incumbent_users_control after week 6)
   → Ship
```

---

## 5. Cannibalization Between Platforms (Каннибализация между платформами)

### **Проблема: Улучшение на одной платформе снижает другую**

```
┌──────────────────────────────────────────────────┐
│ CROSS-PLATFORM CANNIBALIZATION                   │
├──────────────────────────────────────────────────┤
│                                                   │
│ Scenario: A/B test улучшений Car Integration    │
│                                                   │
│ Test Group Results:                              │
│ ✅ Car listening: +40% hours                     │
│ ✅ Car session frequency: +25%                   │
│ ✅ Look like huge win!                           │
│                                                   │
│ But deeper analysis shows:                       │
│ ❌ Mobile listening: -15% hours                  │
│ ❌ Desktop listening: -8% hours                  │
│                                                   │
│ Net Effect:                                      │
│ Total hours: +40% - 15% - 8% = +17%              │
│ Still positive, но не +40%!                      │
│                                                   │
│ Root Cause: Substitution (Замещение)             │
│ Users shifted listening FROM mobile TO car       │
│ NOT adding new listening, just moving it         │
│                                                   │
└──────────────────────────────────────────────────┘
```

**Другие примеры:**

```
1. Smart Speaker improvements
   ✅ Speaker listening: +50%
   ❌ Mobile morning listening: -20% (cannibalized)
   Net: +30% still good

2. Wearables offline mode
   ✅ Watch gym listening: +100% (from zero)
   ❌ Phone gym listening: -60% (substitution)
   Net: +40% (net new listening moments!)

3. Premium feature (offline)
   ✅ Offline listening: +200%
   ❌ Online listening: -10% (shift to offline)
   Net: +190% total hours (good!)
   But: Server costs ↓ (less streaming) - silver lining
```

---

### **Решение 1: Measure Total, Not Just Platform-Specific (Измеряем total, не только специфичное)**

```python
def calculate_net_effect(user_id, test_period):
    """
    Измеряем TOTAL listening across ALL platforms
    """
    platforms = ['mobile', 'web', 'car', 'speaker', 'watch', 'tv']
    
    total_hours = {}
    
    for platform in platforms:
        hours = get_listening_hours(user_id, platform, test_period)
        total_hours[platform] = hours
    
    # Primary metric: TOTAL across all platforms
    total = sum(total_hours.values())
    
    # Secondary: Per-platform breakdown (for diagnosis)
    breakdown = total_hours
    
    return {
        'total_hours': total,  # This is what matters!
        'platform_breakdown': breakdown,
        'cannibalization_detected': detect_cannibalization(breakdown)
    }

def detect_cannibalization(breakdown):
    """
    Проверяем, есть ли значительное снижение на других платформах
    """
    increases = [p for p, h in breakdown.items() if h > baseline[p]]
    decreases = [p for p, h in breakdown.items() if h < baseline[p]]
    
    if len(increases) > 0 and len(decreases) > 0:
        return {
            'cannibalization': True,
            'gaining': increases,
            'losing': decreases,
            'recommendation': 'Analyze if net positive'
        }
    return {'cannibalization': False}
```

---

### **Решение 2: User-Level Total Listening as Primary Metric**

```sql
-- Primary Success Metric: User-level TOTAL listening
SELECT 
    user_id,
    variant,
    
    -- Per-platform (secondary metrics)
    SUM(CASE WHEN platform = 'mobile' THEN hours ELSE 0 END) as mobile_hours,
    SUM(CASE WHEN platform = 'car' THEN hours ELSE 0 END) as car_hours,
    SUM(CASE WHEN platform = 'speaker' THEN hours ELSE 0 END) as speaker_hours,
    -- ... other platforms
    
    -- PRIMARY METRIC: Total across all platforms
    SUM(hours) as total_hours
    
FROM user_listening
WHERE date BETWEEN test_start AND test_end
GROUP BY user_id, variant;

-- Analysis
SELECT 
    variant,
    AVG(total_hours) as avg_total_hours,  -- PRIMARY
    AVG(mobile_hours) as avg_mobile,      -- Secondary
    AVG(car_hours) as avg_car             -- Secondary
FROM above
GROUP BY variant;

-- Decision Rule:
-- Ship if: Test total_hours > Control total_hours
-- Even if some platforms cannibalized (redistribution OK if net positive)
```

---

### **Решение 3: Intent-Based Segmentation (Сегментация по намерению)**

```python
def segment_by_substitution_intent(users):
    """
    Разделяем users по potential for substitution
    """
    segments = {
        'expansion': [],      # Могут добавить новые listening moments
        'substitution': [],   # Скорее всего просто переключатся
        'hybrid': []          # Смешанное поведение
    }
    
    for user in users:
        # Expansion candidates: Low current usage, room to grow
        if user.total_hours_per_week < 5:
            segments['expansion'].append(user)
        
        # Substitution candidates: Already high usage
        elif user.total_hours_per_week > 20:
            segments['substitution'].append(user)
        
        # Hybrid
        else:
            segments['hybrid'].append(user)
    
    return segments

# Analyze separately
for segment_name, segment_users in segments.items():
    effect = analyze_test(segment_users)
    
    if segment_name == 'expansion':
        # Expect: Mostly net new listening (less cannibalization)
        print(f"Expansion segment: {effect}")
    
    elif segment_name == 'substitution':
        # Expect: More platform shifting (higher cannibalization)
        print(f"Substitution segment: {effect}")
```

---

## 6. Sample Ratio Mismatch (SRM) - Несоответствие соотношения выборки

### **Проблема: Control и Test группы не 50/50 как ожидалось**

```
┌──────────────────────────────────────────────────┐
│ SAMPLE RATIO MISMATCH (SRM)                      │
├──────────────────────────────────────────────────┤
│                                                   │
│ Expected:                                        │
│ ├─ Control: 50% (10,000 users)                  │
│ └─ Test: 50% (10,000 users)                     │
│                                                   │
│ Actual:                                          │
│ ├─ Control: 48% (9,600 users) ⚠️               │
│ └─ Test: 52% (10,400 users) ⚠️                 │
│                                                   │
│ Difference: 4% (400 users)                       │
│                                                   │
│ Is this just random chance? Or real problem?     │
│                                                   │
│ Chi-squared test:                                │
│ p-value = 0.003 ❌                               │
│ → Statistically significant imbalance!           │
│ → Something is WRONG with randomization          │
│                                                   │
└──────────────────────────────────────────────────┘
```

**Возможные причины SRM в Звуке:**

```
1. Platform-specific bugs (Баги на конкретной платформе)
   ├─ iOS app: рандомизация работает корректно
   └─ Android app: баг в variant assignment
   → Android users перекошены в Test

2. Crash rates differ by variant (Разные частоты сбоев)
   ├─ Test variant: новый код → higher crash rate
   └─ Crashed users: не попадают в analysis
   → Test group искусственно меньше

3. Network/loading issues (Проблемы сети)
   ├─ Test: heavier assets, slower load
   └─ Users on slow network: bounce before assigned to Test
   → Test underrepresented

4. Triggering logic biased (Смещенная логика триггеров)
   ├─ Test shown only if user has feature X enabled
   └─ Control shown to everyone
   → Imbalanced sample

5. Data logging issues (Проблемы логирования)
   ├─ Control: logs correctly
   └─ Test: occasional logging failures
   → Test appears smaller in data
```

---

### **Решение 1: SRM Check (Обязательная проверка SRM)**

```python
from scipy.stats import chisquare

def check_srm(control_count, test_count, expected_ratio=0.5, alpha=0.001):
    """
    Проверяем Sample Ratio Mismatch
    
    Alpha = 0.001 (very strict!) потому что SRM = red flag
    """
    total = control_count + test_count
    expected_control = total * expected_ratio
    expected_test = total * (1 - expected_ratio)
    
    # Chi-squared test
    observed = [control_count, test_count]
    expected = [expected_control, expected_test]
    
    chi2, p_value = chisquare(observed, expected)
    
    srm_detected = p_value < alpha
    
    if srm_detected:
        actual_ratio = control_count / total
        return {
            'srm_detected': True,
            'p_value': p_value,
            'expected_ratio': expected_ratio,
            'actual_ratio': actual_ratio,
            'severity': 'CRITICAL',
            'action': 'DO NOT SHIP - Investigate root cause',
            'delta': abs(actual_ratio - expected_ratio)
        }
    
    return {
        'srm_detected': False,
        'p_value': p_value,
        'status': 'OK'
    }

# Example usage
result = check_srm(control_count=9600, test_count=10400)

if result['srm_detected']:
    print(f"⚠️ SRM DETECTED! p={result['p_value']}")
    print(f"Expected: 50/50, Actual: {result['actual_ratio']:.1%}")
    print("→ STOP analysis, investigate root cause")
    # DO NOT MAKE DECISIONS BASED ON THIS TEST!
```

---

### **Решение 2: Deep Diagnostic для SRM**

```sql
-- Диагностика SRM: где проблема?

-- 1. By Platform
SELECT 
    platform,
    variant,
    COUNT(*) as users,
    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY platform) as pct
FROM test_users
GROUP BY platform, variant
ORDER BY platform, variant;

-- Expected: ~50/50 на каждой платформе
-- If iOS: 50/50 but Android: 40/60 → Android bug!

-- 2. By Date (cohort stability)
SELECT 
    DATE(assignment_date) as date,
    variant,
    COUNT(*) as users
FROM test_users
GROUP BY date, variant
ORDER BY date, variant;

-- Expected: Stable 50/50 каждый день
-- If ratio drifts over time → logging issue or code deploy problem

-- 3. By User Segment
SELECT 
    user_segment,
    variant,
    COUNT(*) as users,
    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY user_segment) as pct
FROM test_users
GROUP BY user_segment, variant;

-- If certain segments skewed → triggering logic problem
```

---

### **Решение 3: Re-randomization (Повторная рандомизация)**

```
If SRM detected and root cause found:

Option A: Fix and restart test
├─ Fix the bug
├─ Clear previous assignments
└─ Start fresh 50/50 randomization

Option B: Use propensity score matching
├─ Keep existing data
├─ Match Control/Test users by propensity
└─ Reweight to balance groups

Option C: Segment analysis
├─ Find segments with no SRM
├─ Analyze those segments only
└─ Extrapolate carefully to full population
```

---

## 7. Metric Definition Ambiguity (Неоднозначность определения метрик)

### **Проблема: "Слушал ли пользователь?" имеет много определений**

```
┌──────────────────────────────────────────────────┐
│ METRIC DEFINITION AMBIGUITY                      │
├──────────────────────────────────────────────────┤
│                                                   │
│ Question: "Увеличивает ли Test engagement?"     │
│                                                   │
│ Но что такое "engagement" в Звуке?               │
│                                                   │
│ Definition 1: Listening Hours                    │
│ ├─ Test: 15.2 hours/week                         │
│ ├─ Control: 14.8 hours/week                      │
│ └─ Result: +2.7% ✅ Win!                         │
│                                                   │
│ Definition 2: Sessions                           │
│ ├─ Test: 8.2 sessions/week                       │
│ ├─ Control: 9.1 sessions/week                    │
│ └─ Result: -9.9% ❌ Loss!                        │
│                                                   │
│ Definition 3: Tracks Played                      │
│ ├─ Test: 142 tracks/week                         │
│ ├─ Control: 138 tracks/week                      │
│ └─ Result: +2.9% ✅ Win!                         │
│                                                   │
│ Definition 4: Active Days                        │
│ ├─ Test: 4.2 days/week                           │
│ ├─ Control: 4.5 days/week                        │
│ └─ Result: -6.7% ❌ Loss!                        │
│                                                   │
│ SO... Did Test improve engagement or not?? 🤔    │
│                                                   │
│ Answer: Depends on definition!                   │
│ → Need clear PRIMARY metric upfront              │
│                                                   │
└──────────────────────────────────────────────────┘
```

---

### **Решение 1: Pre-register Primary Metric (Предварительная регистрация)**

```python
# BEFORE test starts: Document everything

TEST_PLAN = {
    'test_name': 'new_recommendations_algo_v3',
    'hypothesis': 'New algo increases user engagement',
    
    # PRIMARY METRIC (только одна!)
    'primary_metric': {
        'name': 'total_weekly_listening_hours',
        'definition': '''
            SUM of all audio playback time (in hours) per user per week.
            Includes: music, podcasts, audiobooks
            Excludes: paused time, buffering time
            Minimum qualifying playback: 30 seconds per track
        ''',
        'calculation': '''
            SELECT 
                user_id,
                SUM(playback_duration_sec) / 3600 as weekly_hours
            FROM listening_events
            WHERE playback_duration_sec >= 30
                AND event_type = 'play_completed'
            GROUP BY user_id
        ''',
        'target_lift': '+5%',
        'minimum_detectable_effect': '2%'
    },
    
    # SECONDARY METRICS (can look at, но не для decision)
    'secondary_metrics': [
        'sessions_per_week',
        'tracks_per_week',
        'skip_rate',
        'd7_retention'
    ],
    
    # GUARDRAIL METRICS (must not get worse)
    'guardrail_metrics': [
        'crash_rate': {'max_acceptable': 1.0},  # %
        'buffering_rate': {'max_acceptable': 2.0},  # %
        'd1_retention': {'min_acceptable': -2}  # percentage points
    ],
    
    # DECISION RULES
    'decision_criteria': {
        'ship_if': 'primary_metric lift >= 2% AND p_value < 0.05 AND all guardrails pass',
        'iterate_if': 'primary_metric lift between 0-2% OR guardrails degraded',
        'kill_if': 'primary_metric negative OR critical guardrails failed'
    }
}

# После теста: Analyze ONLY according to pre-registered plan
# NO cherry-picking metrics that happen to be positive!
```

---

### **Решение 2: Metric Hierarchy (Иерархия метрик)**

```
┌──────────────────────────────────────────────────┐
│ METRIC HIERARCHY                                 │
├──────────────────────────────────────────────────┤
│                                                   │
│ Tier 1: PRIMARY (Decision metric)                │
│ └─ Total Weekly Listening Hours                  │
│    → This is THE metric for ship/no-ship         │
│                                                   │
│ Tier 2: SECONDARY (Diagnostic metrics)           │
│ ├─ Sessions per week                             │
│ ├─ Session duration                              │
│ ├─ Tracks played                                 │
│ └─ Active days per week                          │
│ → Help understand WHY primary moved              │
│ → NOT used for decision, only for diagnosis      │
│                                                   │
│ Tier 3: GUARDRAILS (Safety metrics)              │
│ ├─ Crash rate (must not increase)               │
│ ├─ D1 retention (must not drop >2pp)            │
│ └─ NPS (must not decrease significantly)         │
│ → Can VETO a positive primary metric             │
│ → "Wins are only wins if guardrails hold"        │
│                                                   │
│ Tier 4: EXPLORATORY (Insight metrics)            │
│ ├─ Content diversity                             │
│ ├─ Genre distribution shifts                     │
│ └─ Recommendation acceptance rate                │
│ → Generate hypotheses for future tests           │
│ → NO significance testing required               │
│                                                   │
└──────────────────────────────────────────────────┘
```

---

### **Решение 3: Composite Score (Композитный скор) - использовать осторожно!**

```python
def calculate_engagement_score(user_metrics):
    """
    Composite engagement score
    
    Combines multiple dimensions into single score
    Use ONLY if truly necessary (multiple equally important metrics)
    """
    
    # Weighted combination of metrics
    score = (
        0.40 * normalize(user_metrics['listening_hours']) +
        0.25 * normalize(user_metrics['sessions_per_week']) +
        0.20 * normalize(user_metrics['tracks_played']) +
        0.15 * normalize(user_metrics['active_days'])
    )
    
    return score

# Weights должны быть:
# 1. Pre-registered (до теста!)
# 2. Based on business priorities
# 3. Validated through historical correlation with retention/LTV

# Benefit: Single metric для decision
# Risk: Hides what's actually happening, harder to diagnose
```

---

## Summary: Key Takeaways для A/B тестов в Звуке

```
┌──────────────────────────────────────────────────┐
│ A/B TESTING BEST PRACTICES ДЛЯ ЗВУКА             │
├──────────────────────────────────────────────────┤
│                                                   │
│ 1. Network Effects                               │
│    ✅ Use cluster randomization для social fics  │
│    ✅ Consider geo-based splits                  │
│    ✅ Monitor spillover effects                  │
│                                                   │
│ 2. Novelty & Learning                            │
│    ✅ Run tests 4-6 weeks minimum                │
│    ✅ Analyze by maturity cohorts                │
│    ✅ Keep holdout groups long-term              │
│                                                   │
│ 3. Content Effects                               │
│    ✅ Stratify by music preferences              │
│    ✅ Exclude major cultural events              │
│    ✅ Use diff-in-diff for external shocks       │
│                                                   │
│ 4. Cross-Platform                                │
│    ✅ Measure TOTAL listening, not just platform │
│    ✅ Check for cannibalization                  │
│    ✅ Segment by substitution intent             │
│                                                   │
│ 5. Sample Quality                                │
│    ✅ Always check for SRM (p<0.001)             │
│    ✅ Deep diagnostics if SRM detected           │
│    ✅ Don't ship with SRM!                       │
│                                                   │
│ 6. Metric Clarity                                │
│    ✅ Pre-register ONE primary metric            │
│    ✅ Clear metric hierarchy                     │
│    ✅ No post-hoc cherry-picking                 │
│                                                   │
│ 7. Decision Framework                            │
│    ✅ Write decision criteria upfront            │
│    ✅ Guardrails can veto positive primary       │
│    ✅ Separate exploration from confirmation     │
│                                                   │
└──────────────────────────────────────────────────┘
```

Отличный вопрос! Эти нюансы часто оказываются критичными на практике, но их легко упустить при теоретическом обсуждении A/B тестов. На собеседовании демонстрация понимания этих проблем показывает реальный опыт работы с экспериментами в продуктовой аналитике.


# Выбор типа Retention для Звука

Отличный вопрос! Давай разберу, какие типы retention существуют и какой оптимален для Звука.

---

## Типы Retention

### **1. Classic Retention (Return Rate - Коэффициент возврата)**

**Определение:**
```
Day N Retention = (Users active on exactly Day N) / (Users in cohort)
```

**Пример:**
```
Cohort: 1000 пользователей установили 1 января
Day 7: 350 пользователей были активны именно на 7-й день
D7 Retention = 350 / 1000 = 35%
```

**Особенность:** Измеряет, кто вернулся **именно в этот день**

---

### **2. Rolling Retention (Накопительное удержание)**

**Определение:**
```
Day N Rolling Retention = (Users active on Day N OR any day after) / (Users in cohort)
```

**Пример:**
```
Cohort: 1000 пользователей
Day 7: 350 активны на 7-й день + 100 активны позже (но не на 7-й)
D7 Rolling Retention = (350 + 100) / 1000 = 45%
```

**Особенность:** Учитывает всех, кто **когда-либо вернулся** после Day N

---

### **3. Bracket Retention (Retention в окне)**

**Определение:**
```
Week N Retention = (Users active at least once during Week N) / (Users in cohort)
```

**Пример:**
```
Cohort: 1000 пользователей
Week 2 (дни 8-14): 420 пользователей были активны хотя бы 1 день
Week 2 Retention = 420 / 1000 = 42%
```

**Особенность:** Измеряет активность **в временном окне** (неделя, месяц)

---

## Мой выбор для Звука: **Bracket Retention (Weekly/Monthly)**

### **Почему именно Bracket Retention?**

```
┌──────────────────────────────────────────────────┐
│ ОБОСНОВАНИЕ ВЫБОРА                               │
├──────────────────────────────────────────────────┤
│                                                   │
│ 1. Usage Pattern (Паттерн использования)         │
│                                                   │
│ Музыкальный стриминг ≠ ежедневная привычка       │
│ для всех пользователей                           │
│                                                   │
│ Реальность:                                      │
│ ├─ Пн: слушает в дороге ✅                       │
│ ├─ Вт: не слушал ❌                              │
│ ├─ Ср: слушал вечером ✅                         │
│ ├─ Чт: не слушал ❌                              │
│ ├─ Пт: слушал по дороге ✅                       │
│ ├─ Сб: не слушал ❌                              │
│ └─ Вс: слушал дома ✅                            │
│                                                   │
│ Classic D7 Retention = 14% (только если активен  │
│                              ровно в день 7)      │
│ Bracket Week 1 Retention = 57% (активен хотя бы  │
│                                  раз за неделю)   │
│                                                   │
│ ➡️ Bracket честнее отражает engaged users        │
│                                                   │
├──────────────────────────────────────────────────┤
│                                                   │
│ 2. Business Reality (Бизнес-реальность)          │
│                                                   │
│ Нас интересует: "Вернулся ли пользователь       │
│ в этот период?" а не "Вернулся ли ровно в этот  │
│ день?"                                           │
│                                                   │
│ Примеры:                                         │
│ ├─ User A: Активен 5 дней из 7                  │
│ ├─ User B: Активен 1 день из 7                  │
│ └─ User C: Не активен вообще                     │
│                                                   │
│ Classic Retention: Может показать одинаковый     │
│ результат для A и B если они оба не активны      │
│ именно в день измерения                          │
│                                                   │
│ Bracket Retention: Четко разделяет:              │
│ ├─ A и B: Retained ✅ (вернулись)                │
│ └─ C: Churned ❌ (не вернулся)                   │
│                                                   │
├──────────────────────────────────────────────────┤
│                                                   │
│ 3. Stability (Стабильность)                      │
│                                                   │
│ Classic Retention:                                │
│ ├─ Волатильность высокая (день недели matters)   │
│ ├─ Пн-Пт: выше (commute)                         │
│ └─ Сб-Вс: ниже (другие активности)               │
│                                                   │
│ Bracket Retention:                                │
│ ├─ Сглаживает day-of-week эффекты                │
│ ├─ Более стабильная метрика                      │
│ └─ Easier to track trends                        │
│                                                   │
├──────────────────────────────────────────────────┤
│                                                   │
│ 4. Actionability (Применимость для действий)     │
│                                                   │
│ Bracket Retention лучше для:                     │
│ ├─ Setting targets                               │
│ ├─ A/B testing (меньше noise)                    │
│ ├─ Forecasting (более predictable)              │
│ └─ Explaining to stakeholders                    │
│                                                   │
│ "45% пользователей вернулись хотя бы раз         │
│  за первую неделю" - понятно                     │
│                                                   │
│ vs                                               │
│                                                   │
│ "35% были активны ровно на 7-й день" - confusing │
│                                                   │
└──────────────────────────────────────────────────┘
```

---

## Моя Retention Framework для Звука

### **Primary Retention Metrics:**

**1. Weekly Bracket Retention (Основная метрика)**

```sql
-- Определение Weekly Bracket Retention
WITH cohorts AS (
    SELECT 
        user_id,
        DATE_TRUNC('week', first_activity_date) as cohort_week
    FROM users
),

weekly_activity AS (
    SELECT 
        user_id,
        DATE_TRUNC('week', activity_date) as activity_week,
        FLOOR(DATEDIFF(activity_week, cohort_week) / 7) as week_number
    FROM user_activity
    JOIN cohorts USING (user_id)
)

SELECT 
    cohort_week,
    week_number,
    COUNT(DISTINCT user_id) as active_users,
    COUNT(DISTINCT user_id) * 100.0 / 
        (SELECT COUNT(*) FROM cohorts c WHERE c.cohort_week = w.cohort_week) as retention_pct
FROM weekly_activity w
GROUP BY cohort_week, week_number
ORDER BY cohort_week, week_number;
```

**Результат:**
```
Cohort Week: 2025-01-01

Week 0: 100% (1000 users) - по определению
Week 1: 52% (520 users) - вернулись хотя бы раз на 2-й неделе
Week 2: 45% (450 users)
Week 3: 42% (420 users)
Week 4: 40% (400 users) - Month 1 retention
...
Week 12: 32% (320 users) - Quarter retention
```

---

**2. Day-Level Retention (для критичных точек)**

Использую **Classic Retention** только для **ключевых milestone дней:**

```
Day 0 → Day 1 Retention (Next Day Retention)
├─ Самый критичный показатель
├─ Показывает quality onboarding
└─ Target: >50%

Day 1 → Day 7 Retention
├─ Habit formation window
├─ Shows early engagement
└─ Target: >65% (of D1 users)

Week 1 → Week 4 Retention (Month 1)
├─ Product-market fit indicator
├─ Subscription decision point
└─ Target: >75% (of Week 1 retained)
```

**Почему Day 1 особенный:**
- Onboarding либо сработал, либо нет
- Binary outcome (вернулся завтра или нет)
- **Classic Retention здесь уместен**

---

**3. Rolling Retention (для долгосрочного анализа)**

Использую **Rolling Retention** для **long-term health:**

```sql
-- Rolling Retention для long-term view
SELECT 
    cohort_month,
    month_number,
    COUNT(DISTINCT CASE 
        WHEN activity_month >= cohort_month + month_number 
        THEN user_id 
    END) * 100.0 / cohort_size as rolling_retention_pct
FROM user_activity_monthly
GROUP BY cohort_month, month_number;
```

**Использование:**
```
Rolling Retention показывает:
├─ Сколько users "еще с нами" (не churned навсегда)
├─ Plateau level (на каком уровне stabilize)
└─ True churn rate

Example:
Month 0: 100% (cohort)
Month 1: 52% (rolling - вернулись в M1 или позже)
Month 3: 48% (rolling - вернулись в M3 или позже)
Month 6: 45% (rolling - plateau level)
Month 12: 43% (rolling - true loyal users)

Insight: 43% - это core audience, 57% - eventual churn
```

---

## Retention Metrics Hierarchy для Звука

```
┌──────────────────────────────────────────────────┐
│ RETENTION METRICS SYSTEM                         │
├──────────────────────────────────────────────────┤
│                                                   │
│ Level 1: Executive View (Weekly Review)          │
│ ├─ Metric: Week 1 Bracket Retention              │
│ ├─ Type: Bracket (weekly window)                 │
│ ├─ Target: >50%                                  │
│ └─ Why: High-level health indicator              │
│                                                   │
│ Level 2: Product Health (Weekly/Monthly)         │
│ ├─ Week 1, 2, 4, 8, 12 Bracket Retention         │
│ ├─ Type: Bracket (weekly windows)                │
│ ├─ Cohort curves visualization                   │
│ └─ Why: Track retention decay, find inflections  │
│                                                   │
│ Level 3: Critical Milestones (Daily monitoring)  │
│ ├─ D0 → D1 Classic Retention                     │
│ ├─ Type: Classic (next-day return)               │
│ ├─ Target: >50%                                  │
│ └─ Why: Onboarding quality gate                  │
│                                                   │
│ Level 4: Long-term Health (Quarterly)            │
│ ├─ M1, M3, M6, M12 Rolling Retention             │
│ ├─ Type: Rolling (ever returned after)           │
│ ├─ Shows true churn vs dormant                   │
│ └─ Why: LTV forecasting, plateau analysis        │
│                                                   │
│ Level 5: Behavioral Segments (Ad-hoc)            │
│ ├─ By cohort, channel, platform, etc             │
│ ├─ Mix of Bracket & Classic depending on Q       │
│ └─ Why: Deep-dive root cause analysis            │
│                                                   │
└──────────────────────────────────────────────────┘
```

---

## Comparison: Bracket vs Classic vs Rolling для Звука

**Scenario: Cohort of 1000 users, Week 2 activity**

```
User Activity Pattern в Week 2:
├─ 300 users: Активны 5-7 дней
├─ 150 users: Активны 2-4 дня
├─ 50 users: Активны 1 день (именно в день 14)
└─ 500 users: Не активны вообще

Classic D14 Retention:
= 50 / 1000 = 5%
❌ Показывает только тех, кто активен ИМЕННО на день 14
❌ Игнорирует 450 engaged users!

Bracket Week 2 Retention:
= (300 + 150 + 50) / 1000 = 50%
✅ Показывает всех, кто был активен В ТЕЧЕНИЕ Week 2
✅ Честно отражает engagement

Rolling Week 2 Retention:
= (Users active Week 2+ OR any week after) / 1000
= (500 + потенциально больше из будущего) / 1000
= 52%+ (зависит от будущей активности)
⚠️ Depends on future behavior - harder to use for current state
```

**Вывод:** Для Звука **Bracket Retention = sweet spot**

---

## Dashboard Example с правильными Retention типами

```
┌─────────────── RETENTION DASHBOARD ──────────────┐
│                                                   │
│ Primary Metric (Weekly Bracket Retention):       │
│                                                   │
│ Week 1: 52% ✅ (target 50%)                      │
│ Week 2: 45% ✅ (target 42%)                      │
│ Week 4: 38% ⚠️ (target 40%)                     │
│ Week 8: 32% ✅ (target 30%)                      │
│ Week 12: 28% ✅ (target 25%)                     │
│                                                   │
│ [Cohort Retention Curves Chart]                  │
│                                                   │
├───────────────────────────────────────────────────┤
│                                                   │
│ Critical Milestone (Classic Retention):          │
│                                                   │
│ D0 → D1 Retention: 52% ✅ (target 50%)           │
│ This Week: 520 / 1000 new users returned         │
│                                                   │
│ Trend: +3pp vs last week ✅                      │
│                                                   │
├───────────────────────────────────────────────────┤
│                                                   │
│ Long-term Health (Rolling Retention):            │
│                                                   │
│ Month 6 Rolling: 42%                             │
│ Month 12 Rolling: 38%                            │
│                                                   │
│ Interpretation: 38% core loyal audience          │
│ 62% eventual churn (но постепенный)              │
│                                                   │
│ True Monthly Churn: ~3.5%                        │
│                                                   │
└───────────────────────────────────────────────────┘
```

---

## Когда использовать каждый тип

```
┌──────────────────────────────────────────────────┐
│ USE CASE GUIDE                                   │
├──────────────────────────────────────────────────┤
│                                                   │
│ Use BRACKET RETENTION when:                      │
│ ✅ Primary retention metric для стриминга         │
│ ✅ A/B testing retention impact                  │
│ ✅ Setting OKR targets                           │
│ ✅ Explaining to non-technical stakeholders      │
│ ✅ Comparing cohorts over time                   │
│ ✅ Product with irregular usage (не daily)       │
│                                                   │
│ Use CLASSIC RETENTION when:                      │
│ ✅ Day 0 → Day 1 (onboarding critical!)          │
│ ✅ Measuring immediate impact of changes         │
│ ✅ Daily habit products (новости, соцсети)       │
│ ✅ Specific day matters (e.g., "7-day challenge")│
│                                                   │
│ Use ROLLING RETENTION when:                      │
│ ✅ Long-term LTV modeling                        │
│ ✅ Finding plateau/stable retention level        │
│ ✅ Distinguishing dormant vs churned             │
│ ✅ Products with long gaps in usage OK           │
│ ✅ Quarterly/annual strategic planning           │
│                                                   │
└──────────────────────────────────────────────────┘
```

---

## Почему я НЕ выбрал другие типы как primary

### **Classic Retention - Проблемы для Звука:**

```
❌ Problem 1: Day-of-week bias
   Пн-Пт: выше (commute days)
   Сб-Вс: ниже (weekend activities)
   
   Result: Unstable metric, hard to trend

❌ Problem 2: Misses engaged users
   User слушает 4 дня из 7, но не в день измерения
   → Counted as "not retained"
   → Неправильно!

❌ Problem 3: Arbitrary day selection
   Почему Day 7? Почему не Day 6 или Day 8?
   User может быть активен Day 6 и Day 8, но не Day 7
   → Classic shows "not retained" - misleading

❌ Problem 4: Noisy for A/B tests
   Small sample size + day-of-week effects
   → Need huge samples to detect signal
```

### **Rolling Retention - Проблемы для Звука:**

```
❌ Problem 1: Depends on future
   Rolling Week 2 retention depends on Week 3, 4, 5... activity
   → Can't measure "current state" accurately
   → Always changing as users return

❌ Problem 2: Conflates dormant vs retained
   User active Week 2, then dormant Week 3-8, then returns Week 9
   → Still counts as "retained" in Rolling
   → Но мы потеряли его на 7 недель!

❌ Problem 3: Hard to action on
   "Rolling retention dropped 2%"
   → When did they actually leave? Week 2? Week 5?
   → What do we do about it?

❌ Problem 4: Overestimates retention
   Always higher than reality
   → Gives false sense of security
```

---

## Final Answer: **Bracket Retention (Weekly)**

**Summary:**
```
Primary Retention Type: BRACKET (Weekly windows)

Reasons:
1. ✅ Matches music streaming usage patterns (не каждый день)
2. ✅ Stable, actionable metric (меньше noise)
3. ✅ Честно отражает engaged users
4. ✅ Easy to explain and set targets
5. ✅ Works well for A/B testing

Supplementary:
- Classic D0→D1 для onboarding gate
- Rolling M6/M12 для long-term health

Window Size: WEEKLY (7-day brackets)
Why: Достаточно короткий для быстрого feedback,
     достаточно длинный для сглаживания volatility
```

Правильный ли это выбор? Да, потому что он:
- Соответствует бизнес-реальности
- Дает actionable insights
- Minimizes noise
- Максимально полезен для принятия решений

---

Хороший вопрос! Это важная деталь, которую я должен был явно указать с самого начала. В реальности на собеседовании это может быть уточняющий вопрос от интервьюера, и важно уметь объяснить свой выбор.